// THIS FILE WAS GENERATED BY CLAUDE/LLM
// Various tweaking by a human
// Fixed a race condition by hand in run_engine

use std::collections::HashMap;
use assert_cmd::cargo::cargo_bin_cmd;

/// Run the payments engine with the given input file and return stdout
fn run_engine(input_file: &str) -> String {
    let mut cmd = cargo_bin_cmd!("take_home");
    let output = cmd
        .args([input_file])
        .env("NO_LOG", "1")
        .output()
        .expect("Failed to execute command");

    String::from_utf8(output.stdout).unwrap()
}

/// Parse CSV output into a HashMap for order-independent checking
/// Returns: HashMap<client_id, (available, held, total, locked)>
fn parse_output(output: &str) -> HashMap<u16, (String, String, String, bool)> {
    let mut results: HashMap<u16, (String, String, String, bool)> = HashMap::new();
    let lines: Vec<&str> = output.trim().lines().collect();

    if lines.is_empty() {
        return results;
    }

    for line in &lines[1..] {
        let parts: Vec<&str> = line.split(',').collect();
        if parts.len() >= 5 {
            let client: u16 = parts[0].parse().unwrap();
            results.insert(
                client,
                (
                    parts[1].to_string(),
                    parts[2].to_string(),
                    parts[3].to_string(),
                    parts[4] == "true",
                ),
            );
        }
    }

    results
}

/// Run engine and compare output against expected file
fn run_and_compare(test_name: &str) {
    let output = run_engine(&format!("test_data/{}_input.csv", test_name));
    let expected = std::fs::read_to_string(format!("test_data/{}_expected.csv", test_name))
        .expect("Failed to read expected file");

    let output_results = parse_output(&output);
    let expected_results = parse_output(&expected);

    assert_eq!(
        output_results.len(),
        expected_results.len(),
        "{}: client count mismatch. Got {:?}, expected {:?}",
        test_name,
        output_results,
        expected_results
    );

    for (client_id, expected_values) in &expected_results {
        let actual = output_results
            .get(client_id)
            .unwrap_or_else(|| panic!("{}: missing client {}", test_name, client_id));

        assert_eq!(
            actual.0, expected_values.0,
            "{}: client {} available mismatch",
            test_name, client_id
        );
        assert_eq!(
            actual.1, expected_values.1,
            "{}: client {} held mismatch",
            test_name, client_id
        );
        assert_eq!(
            actual.2, expected_values.2,
            "{}: client {} total mismatch",
            test_name, client_id
        );
        assert_eq!(
            actual.3, expected_values.3,
            "{}: client {} locked mismatch",
            test_name, client_id
        );
    }
}

// =============================================================================
// Basic Transaction Tests
// =============================================================================

#[test]
fn test_01_basic_deposits_withdrawals() {
    run_and_compare("01_basic_deposits_withdrawals");
}

#[test]
fn test_02_insufficient_funds() {
    run_and_compare("02_insufficient_funds");
}

#[test]
fn test_14_withdrawal_to_zero() {
    run_and_compare("14_withdrawal_to_zero");
}

#[test]
fn test_24_withdrawal_no_balance() {
    run_and_compare("24_withdrawal_no_balance");
}

// =============================================================================
// Dispute Tests
// =============================================================================

#[test]
fn test_03_dispute() {
    run_and_compare("03_dispute");
}

#[test]
fn test_04_dispute_resolve() {
    run_and_compare("04_dispute_resolve");
}

#[test]
fn test_05_chargeback() {
    run_and_compare("05_chargeback");
}

#[test]
fn test_12_multiple_disputes() {
    run_and_compare("12_multiple_disputes");
}

#[test]
fn test_13_dispute_blocks_withdrawal() {
    run_and_compare("13_dispute_blocks_withdrawal");
}

// =============================================================================
// Error Handling / Edge Cases
// =============================================================================

#[test]
fn test_06_dispute_nonexistent_tx() {
    run_and_compare("06_dispute_nonexistent_tx");
}

#[test]
fn test_07_resolve_not_disputed() {
    run_and_compare("07_resolve_not_disputed");
}

#[test]
fn test_08_chargeback_not_disputed() {
    run_and_compare("08_chargeback_not_disputed");
}

#[test]
fn test_16_locked_account() {
    run_and_compare("16_locked_account");
}

#[test]
fn test_17_dispute_wrong_client() {
    run_and_compare("17_dispute_wrong_client");
}

#[test]
fn test_18_duplicate_tx_id() {
    run_and_compare("18_duplicate_tx_id");
}

#[test]
fn test_19_double_dispute() {
    run_and_compare("19_double_dispute");
}

#[test]
fn test_25_resolve_after_chargeback() {
    run_and_compare("25_resolve_after_chargeback");
}

#[test]
fn test_26_redispute_after_resolve() {
    run_and_compare("26_redispute_after_resolve");
}

// =============================================================================
// Input Format Tests
// =============================================================================

#[test]
fn test_09_decimal_precision() {
    run_and_compare("09_decimal_precision");
}

#[test]
fn test_10_whitespace() {
    run_and_compare("10_whitespace");
}

#[test]
fn test_11_multiple_clients() {
    run_and_compare("11_multiple_clients");
}

#[test]
fn test_15_new_clients_created() {
    run_and_compare("15_new_clients_created");
}

#[test]
fn test_22_empty_amount_field() {
    run_and_compare("22_empty_amount_field");
}

#[test]
fn test_23_max_values() {
    run_and_compare("23_max_values");
}

// =============================================================================
// Complex Scenarios
// =============================================================================

#[test]
fn test_21_complex_scenario() {
    run_and_compare("21_complex_scenario");
}

#[test]
fn test_comprehensive_scenario() {
    run_and_compare("comprehensive_test");
}